# _config.yml

# site settings
title: geekysuavo.github.io
email: geekysuavo@gmail.com
baseurl: ""
url: "http://geekysuavo.github.io"
db: "https://dl.dropboxusercontent.com/u/49207495/website/"
github_username:  geekysuavo

# build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# excluded files
exclude: [README.md, Makefile]

