# _config.yml

# site settings
title: geekysuavo.github.io
email: geekysuavo@gmail.com
baseurl: ""
url: "http://geekysuavo.github.io"
vita: "https://github.com/geekysuavo/vita/raw/main/"
db: "https://github.com/geekysuavo/geekysuavo.github.io/raw/master/"
mj: "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full"
github_username:  geekysuavo

# build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# excluded files
exclude: [README.md, Makefile]

